<template>
    <div class="city-main">
        <div class="city-group">
            <div class="city-title">您的位置</div>
            <div class="native-cityitem city-cityitem">
                <div class="cityitem-group special-group">
                    <div class="native-cityitem-name cityitem-name">北京</div>
                </div>
            </div>
        </div>

        <div class="city-group">
            <div class="city-title">热门城市</div>

			<div class="native-cityitem city-cityitem">
                <div v-for="items in inlandHotInfo" :key="items.name">
					<div class="cityitem-group  special-group hotcity-group">
                    <div class="hotcity-name cityitem-name">{{items.name}}</div>
					</div>
                </div>
            </div>
		</div>

        <div class="city-group">
            <div v-for="letter in letters" :key="letter">
                <div class="city-title">{{letter}}</div>
                <div v-for="item in inlandInfo" :key="item.name">
                    <div class="cityitem-group" v-if="item.pinyin.substr(0,1) == letter">
                        <div class="city-cityitem">	
                            <div class="cityitem-list-name">{{item.name}}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {

	computed: {
		inlandInfo() {
			return this.$store.state.city.inlandInfo;
		},
		inlandHotInfo() {
			return this.$store.state.city.inlandHotInfo;
		},
	},


     data() {
        return {
			letters: ["A","B","C","D","E","F","G","H","J","K","L","M","N","P","Q","R","S","T","W","X","Y","Z"],
			hotcities: [{
				"name": "北京"
			},{
				"name": "西安"
			},{
				"name": "三亚"
			},{
				"name": "丽江"
			},{
				"name": "桂林"
			},{
				"name": "成都"
			},{
				"name": "上海"
			},{
				"name": "西双版纳"
			},{
				"name": "厦门"
			},{
				"name": "长沙"
			},{
				"name": "苏州"
			},{
				"name": "大理"
			},{
				"name": "广州"
			},{
				"name": "杭州"
			},{
				"name": "昆明"
			},{
				"name": "重庆"
			}],
            cities: [{
                "name": "北京",
				"pinyin": "Beijing"
			}, {
				"name": "重庆",
				"pinyin": "Chongqing"
			}, {
				"name": "上海",
				"pinyin": "Shanghai"
			}, {
				"name": "天津",
				"pinyin": "Tianjin"
			}, {
				"name": "长春",
				"pinyin": "Changchun"
			}, {
				"name": "长沙",
				"pinyin": "Changsha"
			}, {
				"name": "常州",
				"pinyin": "Changzhou"
			}, {
				"name": "成都",
				"pinyin": "Chengdu"
			}, {
				"name": "大连",
				"pinyin": "Dalian"
			}, {
				"name": "东莞",
				"pinyin": "Dongguan"
			}, {
				"name": "佛山",
				"pinyin": "Foshan"
			}, {
				"name": "福州",
				"pinyin": "Fuzhou"
			}, {
				"name": "广州",
				"pinyin": "Guangzhou"
			}, {
				"name": "贵阳",
				"pinyin": "Guiyang"
			}, {
				"name": "哈尔滨",
				"pinyin": "Haerbin"
			}, {
				"name": "海口",
				"pinyin": "Haikou"
			}, {
				"name": "邯郸",
				"pinyin": "Handan"
			}, {
				"name": "杭州",
				"pinyin": "Hangzhou"
			}, {
				"name": "合肥",
				"pinyin": "Hefei"
			}, {
				"name": "惠州",
				"pinyin": "Huizhou"
			}, {
				"name": "焦作",
				"pinyin": "Jiaozuo"
			}, {
				"name": "嘉兴",
				"pinyin": "Jiaxing"
			}, {
				"name": "吉林",
				"pinyin": "Jilin"
			}, {
				"name": "济南",
				"pinyin": "Jinan"
			}, {
				"name": "昆明",
				"pinyin": "Kunming"
			}, {
				"name": "兰州",
				"pinyin": "Lanzhou"
			}, {
				"name": "柳州",
				"pinyin": "Liuzhou"
			}, {
				"name": "洛阳",
				"pinyin": "Luoyang"
			}, {
				"name": "南昌",
				"pinyin": "Nanchang"
			}, {
				"name": "南京",
				"pinyin": "Nanjing"
			}, {
				"name": "南宁",
				"pinyin": "Nanning"
			}, {
				"name": "南通",
				"pinyin": "Nantong"
			}, {
				"name": "宁波",
				"pinyin": "Ningbo"
			}, {
				"name": "青岛",
				"pinyin": "Qingdao"
			}, {
				"name": "泉州",
				"pinyin": "Quanzhou"
			}, {
				"name": "沈阳",
				"pinyin": "Shenyang"
			}, {
				"name": "深圳",
				"pinyin": "Shenzhen"
			}, {
				"name": "石家庄",
				"pinyin": "Shijiazhuang"
			}, {
				"name": "苏州",
				"pinyin": "Suzhou"
			}, {
				"name": "台州",
				"pinyin": "Taizhou"
			}, {
				"name": "唐山",
				"pinyin": "Tangshan"
			}, {
				"name": "潍坊",
				"pinyin": "Weifang"
			}, {
				"name": "威海",
				"pinyin": "Weihai"
			}, {
				"name": "武汉",
				"pinyin": "Wuhan"
			}, {
				"name": "无锡",
				"pinyin": "Wuxi"
			}, {
				"name": "厦门",
				"pinyin": "Xiamen"
			}, {
				"name": "西安",
				"pinyin": "Xian"
			}, {
				"name": "许昌",
				"pinyin": "Xuchang"
			}, {
				"name": "徐州",
				"pinyin": "Xuzhou"
			}, {
				"name": "扬州",
				"pinyin": "Yangzhou"
			}, {
				"name": "烟台",
				"pinyin": "Yantai"
			}, {
				"name": "漳州",
				"pinyin": "Zhangzhou"
			}, {
				"name": "郑州",
				"pinyin": "Zhengzhou"
			}, {
				"name": "中山",
				"pinyin": "Zhongshan"
			}, {
				"name": "珠海",
				"pinyin": "Zhuhai"
			}, {
				"name": "阿坝",
				"pinyin": "Aba"
			}, {
				"name": "阿克苏",
				"pinyin": "Akesu"
			}, {
				"name": "阿拉善盟",
				"pinyin": "Alashanmeng"
			}, {
				"name": "大理",
				"pinyin": "Dali"
			}, {
				"name": "丹东",
				"pinyin": "Dandong"
			}, {
				"name": "大庆",
				"pinyin": "Daqing"
			}, {
				"name": "大同",
				"pinyin": "Datong"
			}, {
				"name": "大兴安岭",
				"pinyin": "Daxinganling"
			}, {
				"name": "黄冈",
				"pinyin": "Huanggang"
			}, {
				"name": "黄南",
				"pinyin": "Huangnan"
			}, {
				"name": "黄山",
				"pinyin": "Huangshan"
			}, {
				"name": "黄石",
				"pinyin": "Huangshi"
			}, {
				"name": "呼和浩特",
				"pinyin": "Huhehaote"
			}, {
				"name": "葫芦岛",
				"pinyin": "Huludao"
			}, {
				"name": "呼伦贝尔",
				"pinyin": "Hulunbeier"
			}, {
				"name": "湖州",
				"pinyin": "Huzhou"
			}, {
				"name": "佳木斯",
				"pinyin": "Jiamusi"
			}, {
				"name": "江门",
				"pinyin": "Jiangmen"
			}, {
				"name": "吉安",
				"pinyin": "Jian"
			}, {
				"name": "嘉峪关",
				"pinyin": "Jiayuguan"
			}, {
				"name": "揭阳",
				"pinyin": "Jieyang"
			}, {
				"name": "金昌",
				"pinyin": "Jinchang"
			}, {
				"name": "晋城",
				"pinyin": "Jincheng"
			}, {
				"name": "景德镇",
				"pinyin": "Jingdezhen"
			}, {
				"name": "荆门",
				"pinyin": "Jingmen"
			}, {
				"name": "荆州",
				"pinyin": "Jingzhou"
			}, {
				"name": "金华",
				"pinyin": "Jinhua"
			}, {
				"name": "济宁",
				"pinyin": "Jining"
			}, {
				"name": "晋中",
				"pinyin": "Jinzhong"
			}, {
				"name": "锦州",
				"pinyin": "Jinzhou"
			}, {
				"name": "九江",
				"pinyin": "Jiujiang"
			}, {
				"name": "酒泉",
				"pinyin": "Jiuquan"
			}, {
				"name": "鸡西",
				"pinyin": "Jixi"
			}, {
				"name": "开封",
				"pinyin": "Kaifeng"
			}, {
				"name": "喀什地",
				"pinyin": "Kashidi"
			}, {
				"name": "克拉玛依",
				"pinyin": "Kelamayi"
			}, {
				"name": "克孜勒",
				"pinyin": "Kezile"
			}, {
				"name": "来宾",
				"pinyin": "Laibin"
			}, {
				"name": "莱芜",
				"pinyin": "Laiwu"
			}, {
				"name": "廊坊",
				"pinyin": "Langfang"
			}, {
				"name": "拉萨",
				"pinyin": "Lasa"
			}, {
				"name": "乐山",
				"pinyin": "Leshan"
			}, {
				"name": "凉山",
				"pinyin": "Liangshan"
			}, {
				"name": "连云港",
				"pinyin": "Lianyungang"
			}, {
				"name": "聊城",
				"pinyin": "Liaocheng"
			}, {
				"name": "辽阳",
				"pinyin": "Liaoyang"
			}, {
				"name": "辽源",
				"pinyin": "Liaoyuan"
			}, {
				"name": "丽江",
				"pinyin": "Lijiang"
			}, {
				"name": "临沧",
				"pinyin": "Lincang"
			}, {
				"name": "临汾",
				"pinyin": "Linfen"
			}, {
				"name": "临夏",
				"pinyin": "Linxia"
			}, {
				"name": "临沂",
				"pinyin": "Linyi"
			}, {
				"name": "林芝",
				"pinyin": "Linzhi"
			}, {
				"name": "丽水",
				"pinyin": "Lishui"
			}, {
				"name": "六安",
				"pinyin": "Liuan"
			}, {
				"name": "六盘水",
				"pinyin": "Liupanshui"
			}, {
				"name": "陇南",
				"pinyin": "Longnan"
			}, {
				"name": "龙岩",
				"pinyin": "Longyan"
			}, {
				"name": "娄底",
				"pinyin": "Loudi"
			}, {
				"name": "漯河",
				"pinyin": "Luohe"
			}, {
				"name": "泸州",
				"pinyin": "Luzhou"
			}, {
				"name": "吕梁",
				"pinyin": "Lvliang"
			}, {
				"name": "马鞍山",
				"pinyin": "Maanshan"
			}, {
				"name": "茂名",
				"pinyin": "Maoming"
			}, {
				"name": "眉山",
				"pinyin": "Meishan"
			}, {
				"name": "梅州",
				"pinyin": "Meizhou"
			}, {
				"name": "绵阳",
				"pinyin": "Mianyang"
			}, {
				"name": "牡丹江",
				"pinyin": "Mudanjiang"
			}, {
				"name": "南充",
				"pinyin": "Nanchong"
			}, {
				"name": "南平",
				"pinyin": "Nanping"
			}, {
				"name": "南阳",
				"pinyin": "Nanyang"
			}, {
				"name": "那曲",
				"pinyin": "Naqu"
			}, {
				"name": "内江",
				"pinyin": "Neijiang"
			}, {
				"name": "宁德",
				"pinyin": "Ningde"
			}, {
				"name": "日喀则",
				"pinyin": "Rikaze"
			}, {
				"name": "日照",
				"pinyin": "Rizhao"
			}, {
				"name": "三门峡",
				"pinyin": "Sanmenxia"
			}, {
				"name": "三明",
				"pinyin": "Sanming"
			}, {
				"name": "三亚",
				"pinyin": "Sanya"
			}, {
				"name": "商洛",
				"pinyin": "Shangluo"
			}, {
				"name": "商丘",
				"pinyin": "Shangqiu"
			}, {
				"name": "上饶",
				"pinyin": "Shangrao"
			}, {
				"name": "山南",
				"pinyin": "Shannan"
			}, {
				"name": "汕头",
				"pinyin": "Shantou"
			}, {
				"name": "汕尾",
				"pinyin": "Shanwei"
			}, {
				"name": "韶关",
				"pinyin": "Shaoguan"
			}, {
				"name": "绍兴",
				"pinyin": "Shaoxing"
			}, {
				"name": "邵阳",
				"pinyin": "Shaoyang"
			}, {
				"name": "十堰",
				"pinyin": "Shiyan"
			}, {
				"name": "石嘴山",
				"pinyin": "Shizuishan"
			}, {
				"name": "双鸭山",
				"pinyin": "Shuangyashan"
			}, {
				"name": "朔州",
				"pinyin": "Shuozhou"
			}, {
				"name": "四平",
				"pinyin": "Siping"
			}, {
				"name": "松原",
				"pinyin": "Songyuan"
			}, {
				"name": "绥化",
				"pinyin": "Suihua"
			}, {
				"name": "天水",
				"pinyin": "Tianshui"
			}, {
				"name": "铁岭",
				"pinyin": "Tieling"
			}, {
				"name": "铜川",
				"pinyin": "Tongchuan"
			}, {
				"name": "通化",
				"pinyin": "Tonghua"
			}, {
				"name": "通辽",
				"pinyin": "Tongliao"
			}, {
				"name": "铜陵",
				"pinyin": "Tongling"
			}, {
				"name": "铜仁",
				"pinyin": "Tongren"
			}, {
				"name": "吐鲁番",
				"pinyin": "Tulufan"
			}, {
				"name": "渭南",
				"pinyin": "Weinan"
			}, {
				"name": "文山",
				"pinyin": "Wenshan"
			}, {
				"name": "温州",
				"pinyin": "Wenzhou"
			}, {
				"name": "乌海",
				"pinyin": "Wuhai"
			}, {
				"name": "芜湖",
				"pinyin": "Wuhu"
			}, {
				"name": "乌兰察布",
				"pinyin": "Wulanchabu"
			}, {
				"name": "乌鲁木齐",
				"pinyin": "Wulumuqi"
			}, {
				"name": "武威",
				"pinyin": "Wuwei"
			}, {
				"name": "吴忠",
				"pinyin": "Wuzhong"
			}, {
				"name": "梧州",
				"pinyin": "Wuzhou"
			}, {
				"name": "襄樊",
				"pinyin": "Xiangfan"
			}, {
				"name": "湘潭",
				"pinyin": "Xiangtan"
			}, {
				"name": "湘西",
				"pinyin": "Xiangxi"
			}, {
				"name": "咸宁",
				"pinyin": "Xianning"
			}, {
				"name": "咸阳",
				"pinyin": "Xianyang"
			}, {
				"name": "孝感",
				"pinyin": "Xiaogan"
			}, {
				"name": "锡林郭勒盟",
				"pinyin": "Xilinguolemeng"
			}, {
				"name": "兴安盟",
				"pinyin": "Xinganmeng"
			}, {
				"name": "邢台",
				"pinyin": "Xingtai"
			}, {
				"name": "西宁",
				"pinyin": "Xining"
			}, {
				"name": "新乡",
				"pinyin": "Xinxiang"
			}, {
				"name": "信阳",
				"pinyin": "Xinyang"
			}, {
				"name": "新余",
				"pinyin": "Xinyu"
			}, {
				"name": "忻州",
				"pinyin": "Xinzhou"
			}, {
				"name": "西双版纳",
				"pinyin": "Xishuangbanna"
			}, {
				"name": "宣城",
				"pinyin": "Xuancheng"
			}, {
				"name": "雅安",
				"pinyin": "Yaan"
			}, {
				"name": "延安",
				"pinyin": "Yanan"
			}, {
				"name": "延边",
				"pinyin": "Yanbian"
			}, {
				"name": "盐城",
				"pinyin": "Yancheng"
			}, {
				"name": "阳江",
				"pinyin": "Yangjiang"
			}, {
				"name": "阳泉",
				"pinyin": "Yangquan"
			}, {
				"name": "宜宾",
				"pinyin": "Yibin"
			}, {
				"name": "宜昌",
				"pinyin": "Yichang"
			}, {
				"name": "伊春",
				"pinyin": "Yichun"
			}, {
				"name": "宜春",
				"pinyin": "Yichun"
			}, {
				"name": "伊犁哈萨克",
				"pinyin": "Yilihasake"
			}, {
				"name": "银川",
				"pinyin": "Yinchuan"
			}, {
				"name": "营口",
				"pinyin": "Yingkou"
			}, {
				"name": "鹰潭",
				"pinyin": "Yingtan"
			}, {
				"name": "益阳",
				"pinyin": "Yiyang"
			}, {
				"name": "永州",
				"pinyin": "Yongzhou"
			}, {
				"name": "岳阳",
				"pinyin": "Yueyang"
			}, {
				"name": "玉林",
				"pinyin": "Yulin"
			}, {
				"name": "榆林",
				"pinyin": "Yulin"
			}, {
				"name": "运城",
				"pinyin": "Yuncheng"
			}, {
				"name": "云浮",
				"pinyin": "Yunfu"
			}, {
				"name": "玉树",
				"pinyin": "Yushu"
			}, {
				"name": "玉溪",
				"pinyin": "Yuxi"
			}, {
				"name": "枣庄",
				"pinyin": "Zaozhuang"
			}, {
				"name": "张家界",
				"pinyin": "Zhangjiajie"
			}, {
				"name": "张家口",
				"pinyin": "Zhangjiakou"
			}, {
				"name": "张掖",
				"pinyin": "Zhangye"
			}, {
				"name": "湛江",
				"pinyin": "Zhanjiang"
			}, {
				"name": "肇庆",
				"pinyin": "Zhaoqing"
			}, {
				"name": "昭通",
				"pinyin": "Zhaotong"
			}, {
				"name": "镇江",
				"pinyin": "Zhenjiang"
			}, {
				"name": "中卫",
				"pinyin": "Zhongwei"
			}, {
				"name": "周口",
				"pinyin": "Zhoukou"
			}, {
				"name": "舟山",
				"pinyin": "Zhoushan"
			}, {
				"name": "驻马店",
				"pinyin": "Zhumadian"
			}, {
				"name": "株洲",
				"pinyin": "Zhuzhou"
			}, {
				"name": "淄博",
				"pinyin": "Zibo"
			}, {
				"name": "自贡",
				"pinyin": "Zigong"
			}, {
				"name": "资阳",
				"pinyin": "Ziyang"
			}, {
				"name": "遵义",
				"pinyin": "Zunyi"
			}, {
				"name": "阿城",
				"pinyin": "Acheng"
			}, {
				"name": "安福",
				"pinyin": "Anfu"
			}, {
				"name": "安吉",
				"pinyin": "Anji"
			}, {
				"name": "安宁",
				"pinyin": "Anning"
			}, {
				"name": "安丘",
				"pinyin": "Anqiu"
			}, {
				"name": "安溪",
				"pinyin": "Anxi"
			}, {
				"name": "安义",
				"pinyin": "Anyi"
			}, {
				"name": "安远",
				"pinyin": "Anyuan"
			}, {
				"name": "宝应",
				"pinyin": "Baoying"
			}, {
				"name": "巴彦",
				"pinyin": "Bayan"
			}, {
				"name": "都江堰",
				"pinyin": "Dujiangyan"
			}, {
				"name": "恩平",
				"pinyin": "Enping"
			}, {
				"name": "法库",
				"pinyin": "Faku"
			}, {
				"name": "繁昌",
				"pinyin": "Fanchang"
			}, {
				"name": "方正",
				"pinyin": "Fangzheng"
			}, {
				"name": "浏阳",
				"pinyin": "Liuyang"
			}, {
				"name": "利辛",
				"pinyin": "Lixin"
			}, {
				"name": "溧阳",
				"pinyin": "Liyang"
			}, {
				"name": "沛县",
				"pinyin": "Peixian"
			}, {
				"name": "蓬莱",
				"pinyin": "Penglai"
			}, {
				"name": "上饶",
				"pinyin": "Shangrao"
			}, {
				"name": "上犹",
				"pinyin": "Shangyou"
			}, {
				"name": "上虞",
				"pinyin": "Shangyu"
			}, {
				"name": "尚志",
				"pinyin": "Shangzhi"
			}, {
				"name": "邵武",
				"pinyin": "Shaowu"
			}, {
				"name": "绍兴",
				"pinyin": "Shaoxing"
			}, {
				"name": "沙县",
				"pinyin": "Shaxian"
			}, {
				"name": "嵊泗",
				"pinyin": "Shengsi"
			}, {
				"name": "嵊州",
				"pinyin": "Shengzhou"
			}, {
				"name": "莘县",
				"pinyin": "Shenxian"
			}, {
				"name": "深泽",
				"pinyin": "Shenze"
			}, {
				"name": "歙县",
				"pinyin": "Shexian"
			}, {
				"name": "射阳",
				"pinyin": "Sheyang"
			}, {
				"name": "石城",
				"pinyin": "Shicheng"
			}, {
				"name": "石林",
				"pinyin": "Shilin"
			}, {
				"name": "石狮",
				"pinyin": "Shishi"
			}, {
				"name": "石台",
				"pinyin": "Shitai"
			}, {
				"name": "始兴",
				"pinyin": "Shixing"
			}, {
				"name": "石柱",
				"pinyin": "Shizhu"
			}, {
				"name": "寿光",
				"pinyin": "Shouguang"
			}, {
				"name": "寿宁",
				"pinyin": "Shouning"
			}, {
				"name": "寿县",
				"pinyin": "Shouxian"
			}, {
				"name": "双城",
				"pinyin": "Shuangcheng"
			}, {
				"name": "双流",
				"pinyin": "Shuangliu"
			}, {
				"name": "舒城",
				"pinyin": "Shucheng"
			}, {
				"name": "舒兰",
				"pinyin": "Shulan"
			}, {
				"name": "顺昌",
				"pinyin": "Shunchang"
			}, {
				"name": "沭阳",
				"pinyin": "Shuyang"
			}, {
				"name": "泗洪",
				"pinyin": "Sihong"
			}, {
				"name": "四会",
				"pinyin": "Sihui"
			}, {
				"name": "泗水",
				"pinyin": "Sishui"
			}, {
				"name": "泗县",
				"pinyin": "Sixian"
			}, {
				"name": "泗阳",
				"pinyin": "Siyang"
			}, {
				"name": "嵩明",
				"pinyin": "Songming"
			}, {
				"name": "松溪",
				"pinyin": "Songxi"
			}, {
				"name": "嵩县",
				"pinyin": "Songxian"
			}, {
				"name": "松阳",
				"pinyin": "Songyang"
			}, {
				"name": "遂昌",
				"pinyin": "Suichang"
			}, {
				"name": "遂川",
				"pinyin": "Suichuan"
			}, {
				"name": "睢宁",
				"pinyin": "Suining"
			}, {
				"name": "濉溪",
				"pinyin": "Suixi"
			}, {
				"name": "遂溪",
				"pinyin": "Suixi"
			}, {
				"name": "宿松",
				"pinyin": "Susong"
			}, {
				"name": "宿豫",
				"pinyin": "Suyu"
			}, {
				"name": "太仓",
				"pinyin": "Taicang"
			}, {
				"name": "太和",
				"pinyin": "Taihe"
			}, {
				"name": "泰和",
				"pinyin": "Taihe"
			}, {
				"name": "太湖",
				"pinyin": "Taihu"
			}, {
				"name": "泰宁",
				"pinyin": "Taining"
			}, {
				"name": "台山",
				"pinyin": "Taishan"
			}, {
				"name": "泰顺",
				"pinyin": "Taishun"
			}, {
				"name": "泰兴",
				"pinyin": "Taixing"
			}, {
				"name": "郯城",
				"pinyin": "Tancheng"
			}, {
				"name": "唐海",
				"pinyin": "Tanghai"
			}, {
				"name": "滕州",
				"pinyin": "Tengzhou"
			}, {
				"name": "天长",
				"pinyin": "Tianchang"
			}, {
				"name": "天台",
				"pinyin": "Tiantai"
			}, {
				"name": "桐城",
				"pinyin": "Tongcheng"
			}, {
				"name": "铜鼓",
				"pinyin": "Tonggu"
			}, {
				"name": "通河",
				"pinyin": "Tonghe"
			}, {
				"name": "铜梁",
				"pinyin": "Tongliang"
			}, {
				"name": "铜陵",
				"pinyin": "Tongling"
			}, {
				"name": "桐庐",
				"pinyin": "Tonglu"
			}, {
				"name": "潼南",
				"pinyin": "Tongnan"
			}, {
				"name": "铜山",
				"pinyin": "Tongshan"
			}, {
				"name": "桐乡",
				"pinyin": "Tongxiang"
			}, {
				"name": "通州",
				"pinyin": "Tongzhou"
			}, {
				"name": "武夷山",
				"pinyin": "Wuyishan"
			}, {
				"name": "诸暨",
				"pinyin": "Zhuji"
			}, {
				"name": "遵化",
				"pinyin": "Zunhua"
            }]
        }
     }
          
}
</script>

<style scoped>
.city-main {
    background: #f5f5f5;
}

.city-title {
    background: #f5f5f5;
    color: #616161;
    font-size: .26rem;
    padding-left: .3rem;
    line-height: .54rem;
	display: block;
	border-bottom: .02rem solid #c9cccd;
}
.city-cityitem {
    background: #fff;
    overflow: hidden;
}
.cityitem-group {
    box-sizing: border-box;
}
.cityitem-name {
    display: inline-block;
    border: .02rem solid #c9cccd;
    line-height: .6rem;
    border-radius: .06rem;
    height: .6rem;
    width: 100%;    
}
.special-group {
	padding: .2rem .14rem 0 .1rem;
	width: 33.33%;	
}
.native-cityitem{
    padding-left: .2rem;
    padding-right: .5rem;
    text-align: center;	
    padding-top: .04rem;
    padding-bottom: .26rem;
	border-bottom: .02rem solid #c9cccd;
}
.native-cityitem-name {
    border-color: #00afc7;
    color: #00afc7; 
}

.hotcity-name {
	display: inline-block;
	width: 100%;
}
.hotcity-group {
   	float: left;
}
.cityitem-list-name {
	display: block;
    border-bottom: .02rem solid #c9cccd;
    line-height: .76rem;
    height: .76rem;
    width: 100%; 
	font-size: .28rem;
	padding-left: .2rem;
	color: #212121;
}
</style>

